python run.py random iris
python run.py random iris
python run.py random iris
python run.py random iris
python run.py random iris
python run.py random iris
python run.py random iris
python run.py random iris
python run.py random iris
python run.py random iris

python run.py random mnist
python run.py random mnist
python run.py random mnist
python run.py random mnist
python run.py random mnist
python run.py random mnist
python run.py random mnist
python run.py random mnist
python run.py random mnist
python run.py random mnist